explicitly requires "cv_bridge" package
on package uuv_sensor_ros_plugins, the file "gazebo_ros_image_sonar.cpp" includes
"cv_bridge/cv_bridge.h". This commit fixes the following error:
uuv_simulator/uuv_sensor_plugins/uuv_sensor_ros_plugins/src/gazebo_ros_image_sonar.cpp:50:33: fatal error: cv_bridge/cv_bridge.h: No such file or directory

Signed-off-by: Diego Cesar <dcesar@krakenrobotik.de>